# Generated by Django 3.2.16 on 2022-10-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тестовая модель', 'verbose_name_plural': 'Не забудь удалить'},
        ),
    ]
