# Generated by Django 3.2.16 on 2022-10-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_alter_test_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.AddField(
            model_name='another_product',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.ctg'),
        ),
    ]
