# Generated by Django 3.2.16 on 2022-10-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20221028_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_2',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coffee.product')),
            ],
            options={
                'verbose_name': 'Тестовая модель_2',
                'verbose_name_plural': 'Не забудь удалить_2',
            },
            bases=('coffee.product',),
        ),
    ]
