# Generated by Django 3.2.16 on 2022-10-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_test_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_desc',
            field=models.TextField(blank=True, verbose_name='FULL_DESCRIPTION'),
        ),
    ]
