# Generated by Django 3.2.16 on 2022-11-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='test_2',
        ),
    ]
