# Generated by Django 3.2.16 on 2022-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20221105_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=12, unique=True)),
                ('adress', models.TextField(blank=True, verbose_name='адрес проживания')),
            ],
        ),
    ]
