# Generated by Django 3.2.16 on 2022-11-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0012_auto_20221109_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=150, verbose_name='почта')),
                ('password', models.CharField(db_index=True, max_length=150, verbose_name='пароль')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='coffee.product'),
        ),
    ]
