# Generated by Django 3.2.16 on 2022-11-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_auto_20221114_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_host',
            name='name',
            field=models.CharField(db_index=True, default='email_host', max_length=150, verbose_name='имя-константа'),
        ),
    ]
