# Generated by Django 3.2.16 on 2022-11-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_email_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_host',
            name='name',
            field=models.CharField(db_index=True, default='host_of_email', max_length=150, verbose_name='имя-константа'),
        ),
    ]
