# Generated by Django 3.2.16 on 2022-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0015_alter_email_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_host',
            name='a_email',
            field=models.CharField(db_index=True, default='почта для рассылки смс', max_length=150, verbose_name='почта sms рассылки'),
        ),
        migrations.AddField(
            model_name='email_host',
            name='a_password',
            field=models.CharField(db_index=True, default='пароль для рассылки смс', max_length=150, verbose_name='пароль sms рассылки'),
        ),
    ]
