# Generated by Django 3.2.16 on 2022-11-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0016_auto_20221115_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
