# Generated by Django 3.2.16 on 2022-11-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0017_order_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.TextField(blank=True, verbose_name='адреса')),
                ('cont', models.TextField(blank=True, verbose_name='контакты')),
                ('t_1', models.TextField(blank=True, verbose_name='доп. текст №1')),
                ('t_2', models.TextField(blank=True, verbose_name='доп. текст №2')),
            ],
        ),
    ]
