# Generated by Django 3.2.16 on 2022-11-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0018_footer_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer_content',
            options={'verbose_name': 'информация "подвала"', 'verbose_name_plural': 'информация "подвала"'},
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default='999'),
        ),
    ]
