# Generated by Django 3.2.16 on 2022-12-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0020_auto_20221204_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='район', max_length=200)),
            ],
            options={
                'verbose_name': 'районы доставки',
                'verbose_name_plural': 'районы доставки',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_counted',
            field=models.BooleanField(default=False, verbose_name='в граммах или ед.'),
        ),
    ]
